import { Box, Card, CardContent, Grid } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ChartCards from "../components/ChartCards";
import AtmCard from "../components/AtmCard";
import { DashboardChart } from "../components/DashboardChart";
import Income from "../components/Income";
import LatestTransactions from "../components/LatestTransactions";
import { color } from "@mui/system";
import Analytics from "../components/Analytics";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Grid container spacing={2}>
          <Grid
            item
            container
            sm={12}
            md={6}
            lg={8}
            spacing={2}
            // sx={{ paddin: "1rem 0" }}
          >
            <ChartCards />
            <Grid item xs={12}>
              <Card
                sx={{
                  margin: "1rem 0",
                  background: "var(--accent-2)",
                  borderRadius: "10px",
                  textAlign: "center",
                }}
              >
                <CardContent>
                  <DashboardChart />
                </CardContent>
              </Card>
            </Grid>
            <Grid item xs={12} lg={6}>
              <Income />
            </Grid>
            <Grid item xs={12} lg={6}>
              <LatestTransactions />
            </Grid>
          </Grid>
          <Grid item sm={12} md={6} lg={4}>
            <AtmCard />
            <Box sx={{ margin: "1rem 0" }}>
              <Analytics />
            </Box>
          </Grid>
        </Grid>
      </div>
    </div>
  );
}
