import { Card, CardContent, Grid } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ChartCards from "../components/ChartCards";
import AtmCard from "../components/AtmCard";
import { DashboardChart } from "../components/DashboardChart";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Grid container spacing={2}>
          <Grid item container sm={6} md={8} lg={9} spacing={2}>
            <ChartCards />
            <Grid item xs={12} spacing={2}>
              <Card
                sx={{
                  margin: "1rem 0",
                  background: "var(--accent-2)",
                  borderRadius: "10px",
                  textAlign: "center",
                }}
              >
                <CardContent>
                  <DashboardChart />
                </CardContent>
              </Card>
            </Grid>
          </Grid>
          <Grid item sm={6} md={4} lg={3}>
            <AtmCard />
          </Grid>
        </Grid>
      </div>
    </div>
  );
}
